import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import "../styles/main.css";
import Providers from "@/context/Providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers> {children}</Providers>
      </body>
    </html>
  );
}
